#!/bin/bash

#Where is the inputfile from
INPUT={file-name}
#what is the delimiter, usually working with csv
IFS=","
while read firstname lastname
do
  VAR1="${firstname}.${lastname}"
  VAR2="Cybears21!" #can be whatever you please
  useradd -m -s /bin/bash "$VAR1"
  echo "$VAR1:$VAR2" | chpasswd
done < $INPUT
