#!/bin/bash

#Where is the inputfile from
INPUT={file-name}
#what is the delimiter, usually working with csv
IFS=","
while read firstname lastname
do
  useradd -m "${firstname}.${lastname}"
done < $INPUT
