#!/bin/bash

#This script creates 100 users and it adds even number users
#to a group called ftp and off to a group called ssh

groupadd sshGroup
groupadd ftpGroup

#We are going to put the passwords in pass.txt to prove
#that they are all random

touch pass.txt

for i in {1..100}
do
  #putting user1,user2,etc
  VAR1="user$i"
  VAR2=$(openssl rand -base64 12 )
  
  #this adds the user, makes a home directory and adds a shell
  useradd -m -s /bin/bash $VAR1
  
  #command for batch adding users
  echo "$VAR1:$VAR2" | chpasswd
  #throw them into a txt
  echo "$VAR1:$VAR2" >> pass.txt
  
if [ $(( i%2 )) -eq 0 ]
  then
  sudo usermod -aG ftpGroup $VAR1
else
  sudo usermod -aG sshGroup $VAR1
fi
done
